add gui config
usdot-fhwa-stol/carma-config pull request #100
Opened 2021-01-28 16:04 UTC by itabr

# PR Details
## Description
adding nvidia run time flag to platfrom container

## Related Issue

#894

## Motivation and Context

## How Has This Been Tested?
Deployed and tested on white Pacifica

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-28 16:55 UTC, aswath1 submitted a review, later dismissed

2021-01-28 17:48 UTC, msmcconnell requested changes
We should apply this change to all actual vehicle configs not just the white pacifica.

2021-02-04 16:47 UTC, msmcconnell requested changes
This change is also needed on all the truck configs. 

Also you need to be passing in the cuda argument as true from the vehicle configs but as false from the simulation and development configs.

2021-02-04 16:50 UTC, itabrl commented
discuss with project manager, might need to hold off due to testing.

2021-02-05 16:03 UTC, msmcconnell approved these changes

2021-02-05 16:03 UTC, merged