add launch arguments for guidance.launch
usdot-fhwa-stol/carma-config pull request #162
Opened 2022-02-07 20:05 UTC by adev4a

# PR Details
Updates for launching carma guidance packages.
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-08 20:49 UTC, JonSmet requested changes

2022-02-08 20:49 UTC, JonSmet commented on carla_integration/carma_docker.launch.py
> +    # Declare strategic_plugins_to_validate
Update to `# Declare control_plugins_to_validate` here and in other carma_docker.launch.py files

2022-02-08 20:53 UTC, JonSmet commented
Also, since this PR is to support the carma-platform PR #1603 for porting the mobilitypath_visualizer package to ROS2, let's update the bridge.yml files to include the new ROS2 topics that have been subscribed to or published to that aren't currently listed.

2022-02-10 17:37 UTC, adev4a commented
This PR should be merged after carma-platform PR #1603 mentioned above in order to prevent issues at launch

2022-02-14 15:45 UTC, JonSmet requested changes

2022-02-14 15:45 UTC, JonSmet commented on carla_integration/bridge.yml
> +    topic: /incoming_mobility_path
Since the bridge.yml files include the full topic names, this should be `/message/incoming_mobility_path` here and in the other files.

2022-02-14 15:53 UTC, JonSmet submitted a review, later dismissed

2022-02-15 13:03 UTC, JonSmet requested changes

2022-02-15 13:03 UTC, JonSmet commented on development/bridge.yml
> +<<<<<<< HEAD
This needs to be removed

2022-02-15 13:03 UTC, JonSmet commented on development/bridge.yml
> +=======
This needs to be removed as well

2022-02-15 13:45 UTC, JonSmet approved these changes

2022-02-15 13:45 UTC, merged