Sync dev with 4.2
usdot-fhwa-stol/carma-config pull request #204
Opened 2022-08-03 16:02 UTC by SaikrishnaBairamoni

# PR Details
This PR is to merge release cabin into develop
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-04 20:12 UTC, kjrush requested changes

2022-08-04 20:12 UTC, kjrush commented on freightliner_cascadia_2012_dot_10004/docker-compose-background.yml
> +    image: usdotfhwastol/carma-web-ui:carma-system-4.2.0
Should still be develop

2022-08-04 20:12 UTC, kjrush commented on lexus_rx_450h_2019/docker-compose-background.yml
> +    image: usdotfhwastol/carma-web-ui:carma-system-4.2.0
Should be develop

2022-08-12 15:12 UTC, SaikrishnaBairamoni commented on freightliner_cascadia_2012_dot_10004/docker-compose-background.yml
> +    image: usdotfhwastol/carma-web-ui:carma-system-4.2.0
Updated to develop

2022-08-12 15:12 UTC, SaikrishnaBairamoni commented on lexus_rx_450h_2019/docker-compose-background.yml
> +    image: usdotfhwastol/carma-web-ui:carma-system-4.2.0
updated to develop

2022-08-16 15:06 UTC, kjrush approved these changes

2022-08-16 15:06 UTC, merged