Feature/sensorlib xml rpc
usdot-fhwa-stol/carma-config pull request #276
Opened 2023-10-27 22:05 UTC by davidgayman

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-30 17:34 UTC, EricChen-Lei approved these changes

2023-10-31 12:50 UTC, MishkaMN requested changes

2023-10-31 12:50 UTC, MishkaMN commented on xil_cloud/docker-compose.yml
> +      - ENV CARLA_EGG_DIR="/home/CarlaCDASimAdapter/"
I am adding the comment here just to keep track of the progress. When I had the "ENV" here, it was giving me error saying it cannot contain whitespace. The code change I got from that integration testing is here https://github.com/usdot-fhwa-stol/carma-config/tree/feature/sensor-lib-xml-rpc-test. We encountered an issue where the code freezes on config loading stage. And we are currently waiting on its fixes and integration test on the simulation computer.

2023-10-31 19:29 UTC, MishkaMN commented
Closing in favor of this:
https://github.com/usdot-fhwa-stol/carma-config/pull/277

2023-10-31 19:29 UTC, closed without merging