Cdar 731 add isc scenario
usdot-fhwa-stol/carma-config pull request #313
Opened 2024-02-02 21:49 UTC by MishkaMN

# PR Details
## Description

As we get closer to verification testing, we need a scenario where permissive right turn results in vru collision. This scenario is described in Intersection Safety Challenge project. 
- So in XML file, o I added a pedestrian and a road-side equipment such that the right turn can collide with the pedestrian
- Python file's camera orientation only changed. 

The tester still only need to modify the Python file to change the pedestrian's speed and its trigger distance from the vehicle to start walking. 

## Related Issue

## Motivation and Context
VRU use case verification testing

## How Has This Been Tested?
Sim PC 1

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [X] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
[CDA Telematics Contributing Guide](https://github.com/usdot-fhwa-stol/cda-telematics/blob/main/Contributing.md) 
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-02-05 14:16 UTC, adamlm requested changes

2024-02-05 14:16 UTC, adamlm commented on ail_vru_uc1_scenario/cdasim_config/scenario-runner/vru_collision.py
There is another PR (usdot-fhwa-stol/scenario-runner#3) that is introducing the same new ScenarioRunner scenario. Why do we need duplicate efforts here?

2024-02-05 18:53 UTC, MishkaMN commented on ail_vru_uc1_scenario/cdasim_config/scenario-runner/vru_collision.py
This is to add it to the local cdasim_config folder, so that the tester can freely change the parameter. We also need to have it in that PR so that the scenario-runner can be deployed with this scenario.

2024-02-05 19:08 UTC, adamlm requested changes

2024-02-05 19:08 UTC, adamlm commented on ail_vru_uc1_scenario/cdasim_config/scenario-runner/vru_collision.py
If we need to have it here for testers, there's no point in having in the `scenario-runner` image. The testers will always be using using this one, which will overwrite the one in the image.

2024-02-06 19:38 UTC, MishkaMN commented on ail_vru_uc1_scenario/cdasim_config/scenario-runner/vru_collision.py
I agree that there is a duplicate effort. However, it is easier for a new developer to come and look at the scenario-runner to see available scenarios rather than going to a whole new repository of carma-config. If we didn't need to change the parameters this much (for example a university tester that is okay keeping single set of parameter and is testing something different), we would have just run the scenario stored in scenario-runner without using this docker-compose.yml or cdasim_config folder.

2024-02-07 14:05 UTC, adamlm requested changes

2024-02-07 14:05 UTC, adamlm commented on ail_vru_uc1_scenario/cdasim_config/scenario-runner/vru_collision.py
If internal testers want to come up with new/modified scenarios, those should be added to and tracked in the `scenario-runner`'s pool of scenarios. Using custom bind mount configurations is fine for local/temporary testing, but it is not a long-term solution for our internal development. If we continue along this approach, the two scenarios are guaranteed to diverge.

Third-party users would continue using bind mounts to extend or modify our offering. For long-term solutions, they can either fork our repo or contribute their scenarios back for others to use.

2024-02-07 16:27 UTC, MishkaMN commented on ail_vru_uc1_scenario/cdasim_config/scenario-runner/vru_collision.py
Okay. To avoid possible divergence, I closed the other PR and brought the change here. Other configs in the folder are required for our current deployment anyways, so I am okay only tracking the scenario here for now.

We may need an easier way for tester to change just the parameters without affecting major structure of the scenario. For example, if one scenario were to have 5 parameters to change each with 2 options, we would need to create 32 combinations. If 2 scenarios, it will be 64. It doesn't feel right to lay out all the options like that. However, it is possible and not a big deal. 

Once we figure out the exact parameters that satisfies our data analysis requirements, we can even lay them all out in xml file and assign ids to them. This way, we don't need the docker volume anymore as you are suggesting and just change the number to run a different configuration.

2024-02-07 17:52 UTC, adamlm approved these changes

2024-02-07 17:53 UTC, merged