Update vehicle configuration parameters for CDAR VRU UC testing
usdot-fhwa-stol/carma-config pull request #326
Opened 2024-03-14 15:31 UTC by paulbourelly999

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-03-14 18:58 UTC, MishkaMN commented
Please add back the VehicleConfigParams.yml file. That is not a duplicate file, but meant to provide easy way to modify the parameters in there for the tester just like all other files

2024-03-14 19:13 UTC, MishkaMN requested changes
And also the docker-compose.yml docker volume to it

2024-03-14 20:09 UTC, adamlm requested changes

2024-03-14 20:09 UTC, adamlm commented on ail_vru_uc1_scenario/carma_rosconsole.conf
> +log4j.logger.ros.yield_plugin=DEBUG
This was added during debugging, so it can be safely removed.

2024-03-15 13:41 UTC, paulbourelly999 commented
> Please add back the VehicleConfigParams.yml file. That is not a duplicate file, but meant to provide easy way to modify the parameters in there for the tester just like all other files

I would strongly advise against having a separate VehcileConfigParam file just to avoid having to rebuild carma-config images in our release. This has multiple draw backs:
- Confusing ( Which one is being used, what if they are different)
- Breaking Convention ( Every CARMA Config provides a VehicleConfigParam.yaml file that is built into the image volume, doing something different here may encourage other down the line to also diverge from this convention)
- Duplication ( Requires more maintenance and is more error prone. You make a change in one file and forget to push it to the other file.)

Please let me know  if I am missing something here.

2024-03-15 15:11 UTC, MishkaMN commented
My reasoning to have it in the config folder is because using carma-config image itself has drawbacks. 
- Just changing one parameter is not user friendly at all -> change file + build image + set image just to exactly mirror what I have locally. I'd say let's just change the file and be done with it.
- More importantly, I imagine it is also error prone because the tester may forget to do those extra steps because all other parameter changes only require local file changes. So they may end up doing many runs until after the fact. This error is hard to notice because the actual value being used in the system is hidden from the user although local file shows updated value. We have an opportunity to lessen that room for error for the tester who is doing 100+ runs although it is the tester's responsibility to follow the steps correctly. 

To address your points:
1. 
> Confusing ( Which one is being used, what if they are different)

and 

> Duplication ( Requires more maintenance and is more error prone. You make a change in one file and forget to push it to the other file.)

- I understand there being two file seems confusing and more maintenance. To remedy this, I suggest we actually remove the original file so there is only 1 file. The CDASim is currently REQUIRED to start from specific folder, so there is no breaking change if we have it in the folder and not in the image.

2. 
> Breaking Convention ( Every CARMA Config provides a VehicleConfigParam.yaml file that is built into the image volume, doing something different here may encourage other down the line to also diverge from this convention)

We are doing something new by testing things in simulation now. Just because it is convention doesn't mean it's perfect. We already broke the convention by having all these parameters in one place starting from k900, and it actually served us well. The need for such changes indicate there is something lacking from our current configuration management. It may NOT be the perfect solution that will stick, but I see it as a low-risk experimentation towards that goal.

2024-03-15 15:11 UTC, MishkaMN requested changes
My reasoning to have it in the config folder is because using carma-config image itself has drawbacks.

    Just changing one parameter is not user friendly at all -> change file + build image + set image just to exactly mirror what I have locally. I'd say let's just change the file and be done with it.
    More importantly, I imagine it is also error prone because the tester may forget to do those extra steps because all other parameter changes only require local file changes. So they may end up doing many runs until after the fact. This error is hard to notice because the actual value being used in the system is hidden from the user although local file shows updated value. We have an opportunity to lessen that room for error for the tester who is doing 100+ runs although it is the tester's responsibility to follow the steps correctly.

To address your points:
1.

    Confusing ( Which one is being used, what if they are different)

and

    Duplication ( Requires more maintenance and is more error prone. You make a change in one file and forget to push it to the other file.)

    I understand there being two file seems confusing and more maintenance. To remedy this, I suggest we actually remove the original file so there is only 1 file. The CDASim is currently REQUIRED to start from specific folder, so there is no breaking change if we have it in the folder and not in the image.

    Breaking Convention ( Every CARMA Config provides a VehicleConfigParam.yaml file that is built into the image volume, doing something different here may encourage other down the line to also diverge from this convention)

We are doing something new by testing things in simulation now. Just because it is convention doesn't mean it's perfect. We already broke the convention by having all these parameters in one place starting from k900, and it actually served us well. The need for such changes indicate there is something lacking from our current configuration management. It may NOT be the perfect solution that will stick, but I see it as a low-risk experimentation towards that goal.

2024-03-15 15:48 UTC, paulbourelly999 commented
> My reasoning to have it in the config folder is because using carma-config image itself has drawbacks.
> 
> * Just changing one parameter is not user friendly at all -> change file + build image + set image just to exactly mirror what I have locally. I'd say let's just change the file and be done with it.
> * More importantly, I imagine it is also error prone because the tester may forget to do those extra steps because all other parameter changes only require local file changes. So they may end up doing many runs until after the fact. This error is hard to notice because the actual value being used in the system is hidden from the user although local file shows updated value. We have an opportunity to lessen that room for error for the tester who is doing 100+ runs although it is the tester's responsibility to follow the steps correctly.
> 
> To address your points: 1.
> 
> > Confusing ( Which one is being used, what if they are different)
> 
> and
> 
> > Duplication ( Requires more maintenance and is more error prone. You make a change in one file and forget to push it to the other file.)
> 
> * I understand there being two file seems confusing and more maintenance. To remedy this, I suggest we actually remove the original file so there is only 1 file. The CDASim is currently REQUIRED to start from specific folder, so there is no breaking change if we have it in the folder and not in the image.
> 
> 
> > Breaking Convention ( Every CARMA Config provides a VehicleConfigParam.yaml file that is built into the image volume, doing something different here may encourage other down the line to also diverge from this convention)
> 
> We are doing something new by testing things in simulation now. Just because it is convention doesn't mean it's perfect. We already broke the convention by having all these parameters in one place starting from k900, and it actually served us well. The need for such changes indicate there is something lacking from our current configuration management. It may NOT be the perfect solution that will stick, but I see it as a low-risk experimentation towards that goal.

This is not new. The correct way to change carma configuration is to use `carma config edit` which does not require a rebuild of carma-config. Additional,  simulation being a deviation from traditional carma deployment does not grant us a blank check to break all convention. For other services we did not break convention because there is no convention. CARMA Config as up until now only handled vehicle configurations and does not have a convention for handling any other configuration file. 

If a tester wants to add custom volumes to their deployment for testing I think that is perfectly fine but to commit this as a released changes is very high risk. All follow on simulation scenarios will build on our configuration setup and probably end up slightly diverging from that bade on need and developer preference. Having this in here will contaminate every downstream simulation configuration image with the same duplication

2024-03-15 17:03 UTC, MishkaMN approved these changes
Okay I understand we don't want to break any convention here and give ample time for any new configuration management to be tested and put into practice before actually releasing them. The configs here looks good to me.

2024-03-15 17:31 UTC, merged