add carma messenger cdasim config
usdot-fhwa-stol/carma-config pull request #397
Opened 2024-11-13 18:39 UTC by adev4a

# PR Details
Adds configuration for running carma-messenger with cdasim.
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-14 15:43 UTC, MishkaMN requested changes

2024-11-14 15:43 UTC, MishkaMN commented on xil_carma_messenger/README.md
> +# K900 CARMA Cloud CDASim Integration Scenario
Let's update the README.md to describe what this is about and how it is different than others.

2024-11-14 15:43 UTC, MishkaMN commented on xil_carma_messenger/README.md
> +1) Copy all files in the `cdasim_config/route_config` directory to  directory to `/opt/carma/routes/`
for example, this should also include copying of routes into the /opt/carma/messenger/messenger_1 (OR ask them to create a symlink as you mentioned before)

2024-11-14 15:52 UTC, MishkaMN requested changes

2024-11-14 15:52 UTC, MishkaMN commented on xil_carma_messenger/carma-messenger-docker.launch
> +<?xml version="1.0"?>
we don't need this file since we are only launching messenger_ros2.
And we will add the ros2bag in the docker.launch.py as we discussed offline

2024-11-14 16:03 UTC, MishkaMN commented on xil_carma_messenger/carma-messenger-docker.launch
> +<?xml version="1.0"?>
sorry I meant carma-messenger.launch.py*

2024-11-14 20:02 UTC, MishkaMN requested changes

2024-11-14 20:02 UTC, MishkaMN commented on xil_carma_messenger/README.md
> +1) Copy all files in the `cdasim_config/route_config` directory to  directory to `/opt/carma/routes/` and to `/opt/carma-messenger/messenger_1/`
/opt/carma-messenger/messenger_1/routes isn't it?
and also it looks like the docker-compose is missing the docker-volume for these roures as well? maybe the routes can be shared among different messengers like carma-platform, so it coud look something like:
`/opt/carma-messenger/routes:/opt/carma/routes`

2024-11-14 20:03 UTC, MishkaMN commented on xil_carma_messenger/README.md
> +1) Copy all files in the `cdasim_config/route_config` directory to  directory to `/opt/carma/routes/` and to `/opt/carma-messenger/messenger_1/`
also why was the diagram removed?
if the carma-cloud is still doing the same things and carma vehicles stil going through the same routes, I would keep scenario diagram

2024-11-14 20:07 UTC, adev4a commented on xil_carma_messenger/README.md
> +1) Copy all files in the `cdasim_config/route_config` directory to  directory to `/opt/carma/routes/` and to `/opt/carma-messenger/messenger_1/`
This config will test different scenarios with a platform vehicle and carma-messenger vehicle. The routes are different as well. The diagrams should be updated once the scenario is finalized in integration testing, for now i added an image of the outer loop route where the route will be created.

2024-11-15 15:55 UTC, MishkaMN approved these changes

2024-11-15 15:56 UTC, merged